In [1]:
import sys, os
sys.path.append(os.path.abspath(".."))

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/dataset.csv")
df.head()

,width,spacing,x_coord,y_coord,label
0,41.968918,55.415902,-5.577101,10.044452,0.0
1,49.230640,45.360199,8.829402,-10.758954,0.0
2,57.787601,41.036929,-1.923631,8.367453,0.0
3,48.634041,50.051837,-13.665386,0.405630,0.0
4,48.305596,47.094536,10.231907,-2.229131,0.0


In [3]:
safe = df[df["label"] == 0].drop(columns=["label"]).values
hotspot = df[df["label"] == 1].drop(columns=["label"]).values

In [4]:
print(safe.shape)
print(hotspot.shape)

(1000, 4)
(100, 4)


In [12]:
mu_safe = np.mean(safe, axis=0)
mu_hotspot = np.mean(hotspot, axis=0)

print("Safe mean:", mu_safe)
print("Hotspot mean:", mu_hotspot)

Safe mean: [4.98264012e+01 4.98625513e+01 4.21842398e-01 3.25703004e-02]
Hotspot mean: [30.34232607 20.06189587  3.4498625   1.51184713]


In [7]:
sigma_safe = np.cov(safe, rowvar=False)
sigma_hotspot = np.cov(hotspot, rowvar=False)

print("Safe variance:", sigma_safe)
print("Hotspot variance:", sigma_hotspot)

Safe variance: [[ 23.50757942  -1.2013575    0.12420324  -0.53014293]
 [ -1.2013575   26.93732452   0.24680065   0.7663428 ]
 [  0.12420324   0.24680065 104.83786786   8.29489386]
 [ -0.53014293   0.7663428    8.29489386 105.28018563]]
Hotspot variance: [[ 19.73329459   1.08084747  -7.48093751 -13.09261654]
 [  1.08084747  24.75242146   0.25442665   4.71597423]
 [ -7.48093751   0.25442665 112.11597123 -16.91687942]
 [-13.09261654   4.71597423 -16.91687942  95.79778764]]


In [13]:
import pickle, os

os.makedirs("../results", exist_ok=True)

params = {
    "safe": {"mu": mu_safe, "sigma": sigma_safe},
    "hotspot": {"mu": mu_hotspot, "sigma": sigma_hotspot}
}

with open("../results/gaussian_params.pkl", "wb") as f:
    pickle.dump(params, f)